name: RWX Results
author: ryansch
description: A GitHub Action to show results from Captain and ABQ.

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    RUNNER_DEBUG: "1"
  args:
    - captain
