on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test rwx_results
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run action
        uses: ./ # Uses an action in the root directory
        id: rwx_results
        with:
          rwx-access-token: ${{ secrets.RWX_ACCESS_TOKEN }}
          captain-test-suite-id: kairos-rspec
          captain-branch-name: ar-authorization-edit
          captain-commit-sha: c6579b74148621f07d14b2db051040bbe4ebfa62
          captain-repository: detaso/kairos

      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
