name: Release

on:
  workflow_dispatch:
  pull_request_target:
    types: [closed]
    branches: [main]

permissions:
  contents: read

jobs:
  create_action_images:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: detaso/rwx_results
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1
          platforms: linux/amd64
          provenance: false
          sbom: false
